### PR TITLE
add support for loading data for variables

### PR DESCRIPTION
**Pull request by Loori-R**
Added support for loading data for variables, including log field names and values. This feature allows querying `/select/logsql/field_names` for field names and `/select/logsql/field_values` for field values. 
See [issue #40](https://github.com/VictoriaMetrics/victorialogs-datasource/issues/40).

### CODE REVIEW

**Review by dmitryk-dk — DISMISSED** [review]
LGTM!

**Comment by hagen1778** [comment]
@Loori-R would you mind resolving conflicts for this PR?

**Review by hagen1778 — APPROVED** [review]
Thanks!

**Comment by hagen1778** [comment]
@dmitryk-dk @Loori-R shall we make a release?

**Pull request merged**
