### PR TITLE
add support for variables

### PR DESCRIPTION
**Pull request by Loori-R**
The pull request adds support for variables in queries, including [Grafana's global variables]( https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#global-variables).
 
 #5

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Review by hagen1778 — COMMENTED** [review]
@Loori-R would you mind adding tests to verify that variables are properly propagated to queries?

**Comment by Loori-R** [comment]
@hagen1778, added tests for variable replacement

**Review by hagen1778 — APPROVED** [review]
LGTM

**Pull request merged**
