### PR TITLE
fixbug, stream field filter, syntax error

### PR DESCRIPTION
**Pull request by worker24h**
FixBug: https://github.com/VictoriaMetrics/victorialogs-datasource/issues/109

Replace ` OR ` to `|` When stream field filter.

### CODE REVIEW

**Comment by Loori-R** [comment]
Hi @worker24h, thanks for the pull request!  
I think the logic should be modified in the `interpolateQueryExpr` function, which handles variable interpolation:

https://github.com/VictoriaMetrics/victorialogs-datasource/blob/3ec0861bf1ec88a11c6e9d0f0b4b8823a7c9ebb8/src/datasource.ts#L186-L197

**Comment by worker24h** [comment]
@Loori-R Thanks your comment. But I’m sorry, I had a hard understanding for it. 

Do you mean to replace `OR` to `|` directly?  But it will occur syntax error, e.g.
image

I think the function `interpolateQueryExpr ` shouldn't be modified, because we can't judge if the variables is used to `stream-field` or `query key word`

**Comment by Loori-R** [comment]
> I think the function `interpolateQueryExpr ` shouldn't be modified, because we can't judge if the variables is used to `stream-field` or `query key word`

@worker24h Yes, it seems you are right. Thank you.

**Review by Loori-R — DISMISSED** [review]
LGTM!

**Review by dmitryk-dk — DISMISSED** [review]
LGTM!

**Review by dmitryk-dk — COMMENTED** [review]
Hi @worker24h ! Please check the tests, they should work, and in that place there shouldn't be replace.

**Comment by worker24h** [comment]
> Hi @worker24h ! Please check the tests, they should work, and in that place there shouldn't be replace.

Sorry, I had fixed it, and add a new ut for it. Please code review it again, thanks

@dmitryk-dk @Loori-R

**Review by Loori-R — APPROVED** [review]

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Review by dmitryk-dk — APPROVED** [review]

**Review by Loori-R — APPROVED** [review]

**Review by dmitryk-dk — COMMENTED** [review]
Hi @worker24h ! Your commits were cherry-picked to the https://github.com/VictoriaMetrics/victorialogs-datasource/pull/132 and will be included in the new release. It was done because your commits were unsigned. Please sign your commits in the future 
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
You were mentioned as an author in the PR I merged.

Thank you for your contribution.

**Pull request closed without merging**
